import { useQuery } from '@tanstack/react-query';
import { reportApi } from '../../services/report.service';
import { Card, CardContent } from '../../components/ui/Card';
import { Skeleton } from '../../components/ui/Skeleton';
import { Markdown } from '../../components/ui/Markdown';
import { Calendar, TrendingUp, FileText, BarChart3, GitGraph } from 'lucide-react';
import { useState } from 'react';

type Tab = 'daily' | 'weekly' | 'monthly';

const tabConfig: Record<Tab, { label: string; icon: React.ElementType }> = {
  daily: { label: 'Daily', icon: Calendar },
  weekly: { label: 'Weekly', icon: BarChart3 },
  monthly: { label: 'Monthly', icon: GitGraph },
};

export default function ReportsPage() {
  const [tab, setTab] = useState<Tab>('daily');
  const { data: daily, isLoading: ld } = useQuery({
    queryKey: ['reports', 'daily'],
    queryFn: () => reportApi.getDaily(),
    enabled: tab === 'daily',
  });
  const { data: weekly, isLoading: lw } = useQuery({
    queryKey: ['reports', 'weekly'],
    queryFn: () => reportApi.getWeekly(),
    enabled: tab === 'weekly',
  });
  const { data: monthly, isLoading: lm } = useQuery({
    queryKey: ['reports', 'monthly'],
    queryFn: () => reportApi.getMonthly(),
    enabled: tab === 'monthly',
  });

  const loading = tab === 'daily' ? ld : tab === 'weekly' ? lw : lm;
  const data = tab === 'daily' ? daily : tab === 'weekly' ? weekly : monthly;

  return (
    <div className="animate-fade-in">
      <h2 className="text-[22px] font-extrabold tracking-tight mb-1">Reports</h2>
      <p className="text-xs text-muted-foreground mb-4">AI-generated by Hermes</p>

      <div className="flex gap-2 mb-4">
        {(['daily', 'weekly', 'monthly'] as const).map((t) => {
          const cfg = tabConfig[t];
          const active = tab === t;
          return (
            <button
              key={t}
              onClick={() => setTab(t)}
              className={`flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl text-xs font-semibold transition-all duration-200 ${
                active
                  ? 'bg-primary text-primary-foreground shadow-md shadow-primary/20'
                  : 'bg-card border border-border/50 text-muted-foreground hover:border-border hover:text-foreground/70'
              }`}
            >
              <cfg.icon className="w-3.5 h-3.5" />
              {cfg.label}
            </button>
          );
        })}
      </div>

      <div className="space-y-3">
        {loading ? (
          [1, 2].map((i) => <Skeleton key={i} className="h-32 w-full rounded-xl" />)
        ) : (
          (() => {
            const items = Array.isArray(data) ? data : data ? [data] : [];
            if (items.length === 0)
              return (
                <Card variant="elevated">
                  <CardContent className="py-8 text-center">
                    <div className="w-12 h-12 rounded-full bg-muted mx-auto mb-3 flex items-center justify-center">
                      <FileText className="w-5 h-5 text-muted-foreground/40" />
                    </div>
                    <p className="text-sm text-muted-foreground font-medium">
                      No {tab} reports yet
                    </p>
                  </CardContent>
                </Card>
              );
            return items.map((r, i) => {
              const report = r as Record<string, unknown>;
              const date = report.date || report.week_start || report.month_start;
              const scores =
                report.nutrition_score != null
                  ? [
                      { l: 'Nutrition', s: report.nutrition_score },
                      { l: 'Workout', s: report.workout_score },
                      { l: 'Recovery', s: report.recovery_score },
                      { l: 'Bulking', s: report.bulking_score },
                    ]
                  : null;
              return (
                <Card
                  key={i}
                  variant="elevated"
                  className="animate-fade-in"
                  style={{ animationDelay: `${i * 50}ms` }}
                >
                  <CardContent>
                    {date ? (
                      <div className="flex items-center gap-1.5 mb-2.5 text-xs text-muted-foreground font-medium">
                        <Calendar className="w-3.5 h-3.5 text-primary/60" />
                        {String(date).slice(0, 10)}
                      </div>
                    ) : null}
                    {scores && (
                      <div className="flex gap-2 mb-3 flex-wrap">
                        {scores
                          .filter((s) => s.s != null)
                          .map((s) => (
                            <span
                              key={s.l}
                              className="text-[10px] px-2 py-0.5 rounded-full bg-secondary/80 font-medium flex items-center gap-1"
                            >
                              <TrendingUp className="w-2.5 h-2.5" />
                              {s.l}: {(s.s as number).toFixed(0)}/100
                            </span>
                          ))}
                      </div>
                    )}
                    <div className="p-3 rounded-lg bg-secondary/30">
                      <Markdown content={String(report.content_md || '')} />
                    </div>
                  </CardContent>
                </Card>
              );
            });
          })()
        )}
      </div>
    </div>
  );
}
