import { Link } from 'react-router-dom';
import { Bed, FileText, Settings, ChevronRight } from 'lucide-react';

const links = [
  {
    to: '/recovery',
    icon: Bed,
    label: 'Recovery',
    desc: 'Sleep & energy tracking',
    gradient: 'from-indigo-500/20 to-blue-500/20 text-indigo-400',
  },
  {
    to: '/reports',
    icon: FileText,
    label: 'Reports',
    desc: 'AI-generated by Hermes',
    gradient: 'from-purple-500/20 to-violet-500/20 text-purple-400',
  },
  {
    to: '/settings',
    icon: Settings,
    label: 'Settings',
    desc: 'Targets & personal info',
    gradient: 'from-amber-500/20 to-orange-500/20 text-amber-400',
  },
];

export default function MorePage() {
  return (
    <div className="animate-fade-in">
      <h2 className="text-[22px] font-extrabold tracking-tight mb-1">More</h2>
      <p className="text-xs text-muted-foreground mb-4">Recovery, reports & settings</p>

      <div className="space-y-2.5">
        {links.map(({ to, icon: Icon, label, desc, gradient }, i) => (
          <Link
            key={to}
            to={to}
            className="flex items-center gap-4 px-4 py-4 rounded-xl bg-card border border-border/40 shadow-card hover:shadow-card-hover hover:border-border transition-all duration-200 active:scale-[0.98] animate-fade-in"
            style={{ animationDelay: `${i * 60}ms` }}
          >
            <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${gradient} flex items-center justify-center shrink-0`}>
              <Icon className="w-5 h-5" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-bold">{label}</p>
              <p className="text-[11px] text-muted-foreground mt-0.5 truncate">{desc}</p>
            </div>
            <ChevronRight className="w-4 h-4 text-muted-foreground/50 shrink-0" />
          </Link>
        ))}
      </div>
    </div>
  );
}
